///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String splashWater = 'assets/water.jpg';
  static const String splashText = 'assets/splash_text_logo.png';
  static const String splashWaterForIpad = 'assets/water_ipad.jpg';
  static const String faqsImageIcon = 'assets/FAQ Icon.png';
  static const String aboutAppImageIcon = 'assets/About app icon.png';
  static const String termsAndPolicyImageIcon = 'assets/Terms_Icon.png';
  static const String privacyPolicyImageIcon = 'assets/Privacy_Icon.png';
  static const String LicenseImageIcon = 'assets/license icon.png';
  static const String msgImageIcon = 'assets/email_icon.png';
  static const String phoneImageIcon = 'assets/Phone_icon.png';
  static const String dashboardBackgroundImage = 'assets/Dashboard_background.jpg';
  static const String appBarLogo = 'assets/app_bar_logo.png';
  static const String referIcon = 'assets/refer_icon.png';
  static const String referFormIcon = 'assets/ReferForm_Icon.png';
  static const String trackReferral = 'assets/TrackReferral_Icon.png';
  static const String myAccount = 'assets/MyAccount_Icon.png';
  static const String contactUs = 'assets/contact_us.jpg';
  static const String more = 'assets/More_Icon.png';
  static const String fbIcon = 'assets/FB_icon.png';
  static const String twitterIcon = 'assets/twitterX_icon.png';
  static const String emailIcon = 'assets/email_icon.png';
  static const String textIcon = 'assets/text_icon.png';
  static const String closeIcon = 'assets/close_icon.png';






}